### ISSUE TITLE
More TimeoutErrors

### ISSUE THREAD

**Issue by fwerpers** [fwerpers/timeprof#18]
Timeouts can still occur. Here it seemed to happen in the scheduled data collector function.

Results in the function not completing and no new execution is scheduled, which means no more pings :bug: :bowtie:

```
Traceback (most recent call last):
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/timeprof_bot/data_collection/timeprof_matrix_bot.py", line 482, in run
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     return await coro
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/timeprof_bot/data_collection/timeprof_matrix_bot.py", line 318, in col
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     await self.send_room_message("Previous sample unanswered, saving placeholder label.
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/timeprof_bot/data_collection/timeprof_matrix_bot.py", line 555, in sen
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     await self.room_send(
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/.local/lib/python3.8/site-packages/nio/client/async_client.py", line 1
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     return await self._send(RoomSendResponse, method, path, data, (room_id,))
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/.local/lib/python3.8/site-packages/nio/client/async_client.py", line 7
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     transport_resp = await self.send(
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/.local/lib/python3.8/site-packages/nio/client/async_client.py", line 2
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     return await func(self, *args, **kwargs)
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/.local/lib/python3.8/site-packages/nio/client/async_client.py", line 7
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     return await self.client_session.request(
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _r
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     await resp.start(conn)
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     self._continue = None
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:   File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in _
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]:     raise asyncio.TimeoutError from None
Jan 15 20:40:15 raspberrypi timeprof_matrix_bot.py[19597]: asyncio.exceptions.TimeoutError
```

**Comment by fwerpers** [comment]
Seems like room_send will use the timeout set in the AsyncConfig. Same goes for sync_forever() if the timeout is not set explicitly.
